name: findatree
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - numba
  - scipy
  - tqdm
  - h5py
  - bokeh
  - conda-forge::scikit-learn
  - conda-forge::scikit-image
  - conda-forge::notebook
  - conda-forge::nb_conda_kernels
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::autopep8
  - conda-forge::gdal
  - conda-forge::rasterio
  - conda-forge::opencv
  - conda-forge::pyshp
  - conda-forge::geojson
  - conda-forge::shapely
