name: findatree_test
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - numba
  - scikit-image
  - scipy
  - tqdm
  - h5py
  - bokeh
  - jupyter
  - conda-forge::gdal
  - conda-forge::rasterio
  - conda-forge::opencv
  - conda-forge::pyshp
  - conda-forge::geojson
  - conda-forge::shapely
