name: findatree_v01
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - matplotlib
  - numba
  - scipy
  - numpy
  - rasterio
  - opencv
  - pyshp
  - scikit-image
  - ipykernel
  - ipympl
  - hdbscan
  - tqdm
